#!/usr/bin/env bash
# Set up ESPHome dev environment

set -e

cd "$(dirname "$0")/.."

    python3 -m venv venv

  source venv/bin/activate


if ! [ -x "$(command -v uv)" ]; then
  python3 -m pip install uv
fi

uv pip install setuptools wheel
uv pip install -e ".[dev,test]" --config-settings editable_mode=compat

pre-commit install

script/platformio_install_deps.py platformio.ini --libraries --tools --platforms

mkdir -p .temp

echo
echo
echo "Virtual environment created. Run 'source venv/bin/activate' to use it."
